### ISSUE TITLE
Default header and teaser image sizes

### ISSUE THREAD

**Issue by emeraldjava** [glennsarti/glennsarti.github.io#23]
HI Glenn,

I'm wondering can you confirm the default size you use for the standard header and teaser images for each of your posts. I'm hoping to reuse the same style for my own jekyll site. Have you a script or some automated way to create the two images sizes from the target image?

Regards,
Paul O'Connell 
http://emeraldjava.github.io/

**Comment by glennsarti** [comment]
Hi Paul ( @emeraldjava )

For the teaser images I try to keep them at roughly 500x300px.  For the header I try to keep them at 1200x400 BUT that's a big image so it's not the best over slower internet connections

You can see I have a `header-default` and `teaser-default` in the https://github.com/glennsarti/glennsarti.github.io/tree/master/images directory.

I don't have an automated way, I just manually creating them.

Also,

* Because the teaser and headers are different scales (the header is far more a flat rectangle) I tend to use different images
* Because the header images have white text on them, I generally make them a lot darker than the teaser images

Hope this helps.

Glenn.
